apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmi.fullname" . }}
  labels:
    {{- include "dmi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dmi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dmi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dmi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-dmi-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-dmi-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: aws-dmi-secret
                  key: AWS_ACCOUNT
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "-" "_" }}
              value: {{ $value | quote }}
          {{- end }}
          volumeMounts:
            - mountPath: /db
              name: vol
            - mountPath: /app/src/config.ini
              name: vol-conf
              subPath: config.ini
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: {{ template "dmi.fullname" . }}
        - name: vol-conf
          configMap:
            name: {{ template "dmi.fullname" . }}-config-ini

